[build]
publish = "dist/"
command = "bun run type-check && bun run build"

[build.environment]
NODE_ENV = "production"

[context.dev.environment]
NODE_ENV = "development"

[functions."store-ping-data-background"]
included_files = ["./netlify/functions/store-ping-data-background/*.sql"]

[functions."compare"]
included_files = ["./netlify/functions/compare/*.sql"]

[dev]
command = "bun run bun/serve.ts"
port = 8888
targetPort = 3000
framework = "#custom"

# This redirects the extra paths we want to the index for the SPA to handle on the client.
[[redirects]]
from = "/compare"
to = "/index.html"
status = 200
