[build]
publish = "dist/"
command = "bun run type-check && bun run build"

[build.environment]
NODE_ENV = "production"

[context.dev.environment]
NODE_ENV = "development"

[functions."store-ping-data-background"]
included_files = ["./netlify/functions/store-ping-data-background/*.sql"]

[dev]
command = "bun run bun/serve.ts"
port = 8888
targetPort = 3000
framework = "#custom"
